spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gallery
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  # SQL logs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
