spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gallery?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    # use schema.sql & data.sql NOT only with embedded DB
    initialization-mode: always
    # TODO: delete after Liquibase establishment
    continue-on-error: true
  # SQL logs
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    # logging of sql schema creation & population
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
